# Generated by Django 2.1.15 on 2020-04-27 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autotrd81app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtcorder',
            name='gtc_tatus',
        ),
        migrations.AddField(
            model_name='gtcorder',
            name='gtc_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('ORDERED', 'ORDERED'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED'), ('REV', 'REV'), ('OTH', 'OTH')], default='NEW', max_length=10),
        ),
        migrations.AddField(
            model_name='gtcorder',
            name='quantity',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='fill_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
