# Generated by Django 2.1.15 on 2020-04-28 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autotrd81app', '0002_auto_20200427_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trdDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
